#!/bin/bash

set -e

if [[ -z "$VAGRANT_CLOUD_ACCESS_TOKEN" ]]; then
    echo '$VAGRANT_CLOUD_ACCESS_TOKEN must be set'
    exit 1
fi

VAGRANT_BOX_NAME=${BOX_NAME:-pelton22}
VAGRANT_USER_NAME=${USER_NAME:-shieldsbetter}
VAGRANT_BOX_VERSION=$(cat package.json | jq -r .version)

API="https://vagrantcloud.com/api/v1/box/$VAGRANT_USER_NAME/$VAGRANT_BOX_NAME/version/$VAGRANT_BOX_VERSION"

set -x
if ! http --check-status "$API?access_token=$VAGRANT_CLOUD_ACCESS_TOKEN"; then
    http --check-status POST "https://vagrantcloud.com/api/v1/box/$VAGRANT_USER_NAME/$VAGRANT_BOX_NAME/versions" \
            Authorization:"Bearer $VAGRANT_CLOUD_ACCESS_TOKEN" \
            version:="{\"version\": \"$VAGRANT_BOX_VERSION\"}"
    http --check-status POST \
            "$API/providers/" provider:='{"name":"virtualbox"}' \
            Authorization:"Bearer $VAGRANT_CLOUD_ACCESS_TOKEN"
    http --check-status PUT "$API/release" \
            Authorization:"Bearer $VAGRANT_CLOUD_ACCESS_TOKEN"
fi

FILE_NAME="$VAGRANT_BOX_NAME-$VAGRANT_BOX_VERSION.box"

vagrant destroy --force

export PELTON_VAGRANT_PACKAGING=yes
vagrant up

rm "$FILE_NAME" || true
vagrant package --out "$FILE_NAME"

UPLOAD_PATH=$(
    curl "$API/provider/virtualbox/upload?access_token=$VAGRANT_CLOUD_ACCESS_TOKEN" \
    | jq -r .upload_path)

curl -X PUT --upload-file "$FILE_NAME" "$UPLOAD_PATH"
